export const memories = [
  {
    owner: 'Lynden',
    image:
      'https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fb%2Fb6%2FImage_created_with_a_mobile_phone.png%2F1200px-Image_created_with_a_mobile_phone.png&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FImage&tbnid=L2hxXuK7NBWJmM&vet=12ahUKEwiGkpj_otz9AhWTLH0KHU3IDkMQMygBegUIARCSAQ..i&docid=0JWe7yDOKrVFAM&w=1200&h=900&q=image&ved=2ahUKEwiGkpj_otz9AhWTLH0KHU3IDkMQMygBegUIARCSAQ',
    file: '',
    lat: '51.06311085',
    lng: '-114.08791516800315',
    title: 'Sait',
    description:
      'Hey everyone, there is a memory for you to find left for you on campus',
    address: '1301 16 Ave NW, Calgary, AB T2M 0L4',
    radius: 60,
    isLocked: true,
  },

  {
    owner: 'Mudit',
    lat: '51.1188540',
    lng: '-113.9391065',
    title: 'Chacha ki mast pani puri',
    description: 'mast pani puri che',
    address: 'Pani puri chowk',
    radius: 26,
    isLocked: true,
  },
  {
    owner: 'Harshit',
    image:
      'https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fimage&psig=AOvVaw0tVEpY2RT6xWhdt3nGZgLa&ust=1678912610200000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCLiu-YGj3P0CFQAAAAAdAAAAABAE',
    file: '',
    lat: '51.1086567',
    lng: '-113.7391045',
    title: 'Chachas hut',
    description: 'fast food',
    address: 'chachas hut calgary',
    radius: 50,
    isLocked: true,
  },
  {
    owner: 'Param',
    image:
      'https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fimage&psig=AOvVaw0tVEpY2RT6xWhdt3nGZgLa&ust=1678912610200000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCLiu-YGj3P0CFQAAAAAdAAAAABAE',
    file: '',
    lat: '51.1082556',
    lng: '-113.9391076',
    title: 'Raju momo vala',
    description: 'bdiya momein chabao, dil khush kr jao',
    address: 'Raju momo vala, gate no 4, greater calgary',
    radius: 50,
    isLocked: true,
  },
  {
    owner: 'Lynden',
    image:
      'https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fb%2Fb6%2FImage_created_with_a_mobile_phone.png%2F1200px-Image_created_with_a_mobile_phone.png&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FImage&tbnid=L2hxXuK7NBWJmM&vet=12ahUKEwiGkpj_otz9AhWTLH0KHU3IDkMQMygBegUIARCSAQ..i&docid=0JWe7yDOKrVFAM&w=1200&h=900&q=image&ved=2ahUKEwiGkpj_otz9AhWTLH0KHU3IDkMQMygBegUIARCSAQ',
    file: '',
    lat: '51.106542',
    lng: '-113.8991090',
    title: 'The Bar',
    description: 'good vibes',
    address: 'the bar, calgary chowk',
    radius: 50,
    isLocked: true,
  },
  {
    owner: 'Komal',
    image:
      'https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fimage&psig=AOvVaw0tVEpY2RT6xWhdt3nGZgLa&ust=1678912610200000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCLiu-YGj3P0CFQAAAAAdAAAAABAE',
    file: '',
    lat: '51.16455411',
    lng: '-113.8391097',
    title: 'Pizza shop',
    description: 'bekar pizza',
    address: 'Pizza shop, calgary bazaar',
    radius: 50,
    isLocked: true,
  },
  {
    radius: 30,
    owner: 'Salazar Schwartz',
    address: '177 Catherine Street, Starks, Florida, 424',
    title: 'Patsy House title',
    description:
      'Exercitation ex irure excepteur voluptate consectetur consectetur duis minim magna id. Commodo do ipsum aute fugiat et. Laborum et laborum exercitation velit excepteur dolor cupidatat exercitation officia elit. Quis nulla ex aliquip velit incididunt exercitation ut nostrud nisi commodo enim. Ipsum fugiat cupidatat eiusmod qui fugiat irure anim incididunt aute ad eiusmod id tempor irure. Consectetur aliquip culpa id nulla occaecat sint officia dolor esse aliquip irure laboris.\r\n',
    lat: 72.400128,
    lng: 124.966991,
    isLocked: true,
  },
  {
    radius: 29,
    owner: 'Dudley Wolfe',
    address: '309 Norfolk Street, Gloucester, Palau, 4043',
    title: 'Jarvis Bowman title',
    description:
      'Aliqua do tempor anim ipsum id et sunt Lorem consequat laboris aliquip. Lorem velit sint ullamco deserunt consectetur non proident Lorem qui mollit reprehenderit reprehenderit. Velit cillum qui id minim eiusmod culpa in Lorem consectetur dolore ipsum magna.\r\n',
    lat: 45.446853,
    lng: 31.803687,
    isLocked: true,
  },
  {
    radius: 31,
    owner: 'Lori Fitzpatrick',
    address: '840 Matthews Court, Oceola, Vermont, 3858',
    title: 'Elva Riley title',
    description:
      'Do adipisicing occaecat eu aliqua duis sint cupidatat elit ea aliqua exercitation. Id commodo id nulla sunt velit esse cillum occaecat enim consectetur reprehenderit. Esse qui consequat voluptate quis. Laboris laboris est velit nulla est aute. Nulla velit exercitation incididunt aliquip non cupidatat incididunt aute labore magna. Et irure non do ut sunt aute.\r\n',
    lat: -42.406017,
    lng: 163.836255,
    isLocked: true,
  },
  {
    radius: 25,
    owner: 'Jocelyn Barrett',
    address: '506 Richmond Street, Coral, Georgia, 829',
    title: 'Jimenez Copeland title',
    description:
      'Deserunt amet mollit commodo nostrud deserunt id enim do. Qui voluptate adipisicing exercitation sit labore adipisicing velit eiusmod proident nostrud exercitation ea pariatur. Qui officia nulla nulla consectetur in excepteur. Lorem ut deserunt cillum occaecat ea nisi sint et commodo nulla laboris do occaecat nisi. Tempor est minim duis nisi incididunt. Veniam do elit commodo ipsum veniam cupidatat cillum do cupidatat labore veniam nisi. Dolore tempor laboris nisi veniam sit.\r\n',
    lat: -8.561186,
    lng: -146.9661,
  },
  {
    radius: 40,
    owner: 'Morton Armstrong',
    address: '219 Delevan Street, Lorraine, Oklahoma, 3056',
    title: 'Candace Brock title',
    description:
      'Laborum laboris magna excepteur dolore adipisicing deserunt eiusmod eiusmod deserunt aliqua quis Lorem. Sint culpa consectetur deserunt aliquip sit do. Officia fugiat ex aliquip ea laboris sunt magna anim.\r\n',
    lat: 4.073492,
    lng: -88.667038,
  },
  {
    radius: 24,
    owner: 'Paula Gibson',
    address: '654 School Lane, Trexlertown, Washington, 9006',
    title: 'Fox Serrano title',
    description:
      'Eiusmod eiusmod elit laboris ex aliqua in nisi do officia veniam ad excepteur enim. Proident nostrud aliquip ex ad ad. Et do fugiat ex cillum reprehenderit sunt proident eu. Et consectetur est qui duis.\r\n',
    lat: 15.893787,
    lng: -114.278816,
  },
  {
    radius: 36,
    owner: 'Debora Downs',
    address: '615 Summit Street, Sheatown, Kentucky, 4262',
    title: 'Claudette Ruiz title',
    description:
      'Fugiat veniam enim reprehenderit Lorem officia id. Ex aliquip quis magna nisi ad eu minim ullamco amet laborum consectetur esse aliqua. Nisi excepteur laborum labore commodo culpa qui culpa sint ea incididunt. Ex laboris quis eu id. Est aliquip occaecat aliquip commodo magna nisi. Mollit elit pariatur amet aliquip esse.\r\n',
    lat: -58.37113,
    lng: -79.569326,
  },
  {
    radius: 26,
    owner: 'Ilene Bullock',
    address: '411 Crown Street, Tioga, Maine, 103',
    title: 'Freda Farley title',
    description:
      'Lorem eu voluptate sunt aute veniam. Pariatur sunt voluptate velit cupidatat ullamco commodo pariatur aute elit reprehenderit. Nostrud deserunt exercitation mollit do officia sit laborum. Proident ad culpa ullamco ad esse occaecat voluptate deserunt. Velit anim est consequat dolore irure. Incididunt esse ut amet occaecat laboris ut in aliquip irure. Consequat enim tempor sint pariatur voluptate elit exercitation ipsum culpa.\r\n',
    lat: 58.320267,
    lng: 77.25325,
  },
  {
    radius: 28,
    owner: 'Mercado Garza',
    address: '852 Elliott Place, Wakarusa, New Jersey, 2123',
    title: 'Irwin Newman title',
    description:
      'Veniam amet minim dolore eiusmod est velit. Ex culpa in cupidatat anim consequat labore consequat magna enim. Enim qui ut incididunt eu duis ut Lorem consectetur adipisicing magna amet ipsum sunt. Consectetur incididunt fugiat cillum minim fugiat. Minim in officia quis mollit mollit est minim amet ad labore est velit.\r\n',
    lat: 0.303024,
    lng: 159.167316,
  },
  {
    radius: 29,
    owner: 'Juliette Cannon',
    address: '950 Gerald Court, Jennings, Maryland, 4564',
    title: 'Madge Matthews title',
    description:
      'Nostrud quis exercitation exercitation ipsum. Ea ut nisi nisi consectetur mollit. Officia elit proident eiusmod ipsum ullamco minim reprehenderit velit qui nostrud mollit. Elit ut quis ullamco dolor cupidatat dolor ex velit consectetur laboris sit adipisicing. Lorem anim ullamco consectetur quis pariatur esse consequat sit non laborum.\r\n',
    lat: -47.237431,
    lng: -40.394913,
  },
  {
    radius: 29,
    owner: 'Samantha Boyd',
    address: '140 Rapelye Street, Harviell, Alabama, 1985',
    title: 'Cooley Haynes title',
    description:
      'Lorem adipisicing ut fugiat commodo in amet consectetur amet ex dolor id aliquip labore. Eiusmod anim voluptate minim culpa quis do quis reprehenderit proident non adipisicing irure. Dolor reprehenderit enim exercitation officia commodo velit ullamco eiusmod culpa cillum ad ipsum irure. Do tempor consectetur sint ipsum qui dolor. Consectetur Lorem pariatur aute minim ullamco ad proident. Tempor fugiat adipisicing ipsum mollit labore occaecat incididunt commodo voluptate cupidatat. Dolore aute culpa exercitation duis non.\r\n',
    lat: 27.079185,
    lng: -167.457965,
  },
  {
    radius: 39,
    owner: 'Imogene Burgess',
    address: '295 Gates Avenue, Chemung, Utah, 7416',
    title: 'Wilcox Stafford title',
    description:
      'Mollit ipsum ad quis aliquip consectetur minim aliquip. Culpa voluptate esse esse incididunt quis excepteur irure. Consectetur cupidatat aliquip aliquip elit est sint cillum voluptate eu. Reprehenderit nostrud duis sint deserunt cillum ullamco cupidatat aute excepteur elit.\r\n',
    lat: 29.930911,
    lng: -164.455688,
  },
  {
    radius: 39,
    owner: 'Heidi Mclaughlin',
    address: '665 Wythe Avenue, Ellerslie, Virgin Islands, 2224',
    title: 'Rowena Mckee title',
    description:
      'Aliqua sit sint et occaecat ut ad esse enim eu irure. Ex pariatur nisi in proident nulla sit tempor deserunt aliqua quis culpa tempor. Anim aliqua consectetur aute eiusmod cupidatat sunt exercitation nulla qui cillum consequat. Ex fugiat aute sunt ipsum ex in fugiat. Minim Lorem sunt nostrud do eiusmod mollit dolore quis deserunt.\r\n',
    lat: -79.013456,
    lng: 130.415175,
  },
  {
    radius: 39,
    owner: 'Lynda Perez',
    address: '430 Apollo Street, Torboy, American Samoa, 768',
    title: 'Moses Meadows title',
    description:
      'Aliquip labore in do reprehenderit culpa enim. Commodo cupidatat nulla nulla nostrud fugiat laboris ullamco qui culpa irure. Eu nostrud ea consequat irure mollit esse. Ad commodo irure duis excepteur ut dolore exercitation commodo eiusmod nisi sit nostrud ut ad. Proident consequat mollit sunt cillum enim voluptate ex tempor proident commodo enim laboris.\r\n',
    lat: -4.787334,
    lng: 78.313182,
  },
  {
    radius: 34,
    owner: 'Lessie Stout',
    address: '699 Pershing Loop, Knowlton, Louisiana, 8356',
    title: 'Vang Coffey title',
    description:
      'Non excepteur nulla sit sit laboris ad. Do quis ipsum consectetur aute ea tempor in ea dolore reprehenderit nulla amet dolor excepteur. Qui occaecat minim est nulla sint aute aliqua do voluptate voluptate nisi magna. Veniam Lorem deserunt elit officia velit nisi consequat consectetur nostrud deserunt. Cillum nostrud pariatur ea aute laborum fugiat duis qui dolor incididunt irure sint sint sit. Commodo dolor elit occaecat Lorem. Ullamco aliqua officia commodo ut do laboris.\r\n',
    lat: 84.06251,
    lng: -162.140529,
  },
  {
    radius: 40,
    owner: 'Cheri White',
    address: '914 Debevoise Avenue, Frystown, New York, 1892',
    title: 'Gena Nelson title',
    description:
      'Mollit ex elit aute laboris aute deserunt adipisicing. Commodo fugiat sunt aute culpa reprehenderit exercitation excepteur. Sunt aliquip est sunt sit aliqua et nostrud ea nostrud esse. Laboris incididunt sint id adipisicing magna laborum id.\r\n',
    lat: 89.188299,
    lng: 1.829758,
  },
  {
    radius: 30,
    owner: 'Garza Cruz',
    address: '488 Polhemus Place, Fairhaven, Michigan, 5445',
    title: 'Holland Morton title',
    description:
      'Magna ad officia ipsum ea nostrud. Proident elit excepteur aute duis do culpa deserunt proident. Id non duis minim nostrud esse proident voluptate minim eiusmod tempor tempor.\r\n',
    lat: -38.626469,
    lng: -153.531378,
  },
  {
    radius: 39,
    owner: 'Foster Obrien',
    address: '431 Madoc Avenue, Omar, Iowa, 6996',
    title: 'Laurel Cox title',
    description:
      'Tempor mollit laborum proident dolor enim consequat velit laboris. Proident mollit dolore ut cupidatat sit enim et ex anim exercitation laboris. In excepteur commodo officia eu. Qui nisi est exercitation occaecat eu proident consectetur veniam officia sit officia. Mollit enim mollit officia laboris adipisicing mollit commodo officia.\r\n',
    lat: 42.248566,
    lng: -55.926402,
  },
  {
    radius: 24,
    owner: 'Patrica Carver',
    address: '165 Radde Place, Hackneyville, Nevada, 5842',
    title: 'Janet Atkins title',
    description:
      'Consectetur ea amet esse consequat dolor non eu. Consectetur reprehenderit id fugiat aute enim ad sint excepteur do aliqua laborum consequat ut. Proident aliqua sunt eiusmod voluptate laboris dolor irure mollit elit consequat consectetur et laborum nulla.\r\n',
    lat: -16.204052,
    lng: -123.290699,
  },
  {
    radius: 24,
    owner: 'Fry Hodge',
    address:
      '857 Rockaway Avenue, Chamizal, Federated States Of Micronesia, 246',
    title: 'Randi Mosley title',
    description:
      'Cillum mollit mollit non ullamco non. Est cupidatat fugiat amet commodo aliquip ad ex do fugiat. Anim enim duis ut dolore reprehenderit est tempor ut ullamco labore id officia aute.\r\n',
    lat: -24.952477,
    lng: 88.07575,
  },
  {
    radius: 32,
    owner: 'Fields Noel',
    address: '977 Brevoort Place, Richmond, Colorado, 478',
    title: 'Malone Huber title',
    description:
      'Deserunt amet aute do Lorem. Do labore ex ex veniam occaecat exercitation in irure adipisicing laboris quis aliqua sit. Laboris veniam aliqua irure officia nisi dolor irure in deserunt deserunt reprehenderit.\r\n',
    lat: -72.371134,
    lng: -20.332759,
  },
  {
    radius: 32,
    owner: 'Joyce Henry',
    address: '460 Bristol Street, Goodville, Northern Mariana Islands, 5815',
    title: 'Puckett Abbott title',
    description:
      'Laborum id ullamco ad enim ea ullamco dolor voluptate ex ullamco magna exercitation laborum. Nisi ea qui sunt reprehenderit Lorem et mollit exercitation officia tempor cillum commodo. Est non ut adipisicing deserunt excepteur id cillum nisi commodo dolor cillum sunt sint amet. Amet adipisicing in nostrud labore proident aliqua dolor. Non duis eiusmod sit ad sint incididunt eu velit aute. Duis nulla ullamco ipsum ad nostrud dolore excepteur laborum ullamco proident sit irure elit. Laboris mollit nisi in esse deserunt adipisicing quis tempor anim anim commodo proident.\r\n',
    lat: 6.227069,
    lng: -156.946968,
  },
  {
    radius: 39,
    owner: 'Delores Padilla',
    address: '269 Nassau Street, Linganore, Idaho, 1705',
    title: 'Andrea Moreno title',
    description:
      'Pariatur id cupidatat do veniam ex est. Proident mollit ad et esse sint elit. Nostrud velit labore cillum dolor amet aliqua amet. Ea elit nisi esse ex. Exercitation consequat ea cillum aliqua ullamco laborum Lorem dolor reprehenderit consequat amet esse. Duis nostrud laboris esse excepteur amet adipisicing ad sunt. Veniam ipsum magna aliqua occaecat ipsum id.\r\n',
    lat: 82.890538,
    lng: 120.352526,
  },
  {
    radius: 38,
    owner: 'Leona Wilkerson',
    address: '367 Hudson Avenue, Lewis, Puerto Rico, 2663',
    title: 'Sawyer Wade title',
    description:
      'Culpa et amet cupidatat sint aute sint et commodo proident sint ex esse excepteur. Magna tempor in consectetur anim mollit. Do eu in tempor mollit irure sit ipsum duis consequat. Cillum minim velit cillum cupidatat pariatur id labore aute nostrud elit deserunt magna. Pariatur in est esse est fugiat. Cupidatat consectetur aliqua deserunt consectetur aliqua minim velit occaecat reprehenderit ipsum duis. Non Lorem cupidatat incididunt proident Lorem ex veniam sunt irure amet.\r\n',
    lat: -58.397095,
    lng: -144.462071,
  },
  {
    radius: 30,
    owner: 'Evans Snider',
    address: '551 Kaufman Place, Brantleyville, Nebraska, 8285',
    title: 'Rosa Gregory title',
    description:
      'Officia laboris mollit fugiat aute sit qui sint cupidatat nisi esse ullamco tempor eu. Sint in culpa qui elit aliqua nostrud nostrud aute excepteur. Exercitation fugiat aliquip commodo sunt magna. Do eu reprehenderit ea eu laborum non ipsum eiusmod consequat.\r\n',
    lat: 80.187647,
    lng: 13.678576,
  },
  {
    radius: 27,
    owner: 'Vaughn Mann',
    address: '831 Calder Place, Welch, Massachusetts, 8392',
    title: 'Eaton Ramos title',
    description:
      'Labore voluptate velit irure dolor nisi et Lorem nostrud ex proident labore ullamco. Ipsum duis ad incididunt nostrud. Sint qui et adipisicing fugiat. Proident commodo aute aliquip labore eu.\r\n',
    lat: -19.351247,
    lng: 177.600342,
  },
  {
    radius: 20,
    owner: 'Jamie Porter',
    address: '851 Denton Place, Coaldale, Delaware, 7183',
    title: 'Duncan Dudley title',
    description:
      'Cupidatat eiusmod cillum non labore sunt mollit ut pariatur reprehenderit dolor occaecat sint velit. Et Lorem ex nostrud labore sunt velit velit proident cupidatat. Eu aute ut sint incididunt do quis enim ex. Dolor consequat reprehenderit reprehenderit in elit id reprehenderit nostrud exercitation anim.\r\n',
    lat: -75.360102,
    lng: -95.783022,
  },
  {
    radius: 36,
    owner: 'Rebekah Hensley',
    address: '933 Degraw Street, Morgandale, Arizona, 2732',
    title: 'Chasity Bowen title',
    description:
      'Nulla commodo sunt officia anim. Proident veniam id ex ipsum exercitation ipsum laboris occaecat anim officia. Enim magna amet consectetur occaecat reprehenderit anim ullamco sit amet cupidatat eiusmod esse excepteur. Fugiat amet aliqua ipsum proident labore ut qui occaecat enim do officia. Id in occaecat pariatur eiusmod laboris quis in laboris laboris. Laborum labore Lorem duis ipsum dolore qui sunt. Reprehenderit exercitation aliqua aliqua magna do elit id commodo eiusmod adipisicing duis exercitation ea esse.\r\n',
    lat: 22.591334,
    lng: -59.857891,
  },
  {
    radius: 24,
    owner: 'Marisa Holmes',
    address: '527 Stockholm Street, Wollochet, District Of Columbia, 6857',
    title: 'Sadie Lancaster title',
    description:
      'Pariatur aute cillum exercitation mollit eu duis aliquip nulla pariatur. Nostrud nisi sit duis veniam id elit mollit duis adipisicing. Sit consequat mollit ea velit amet sunt pariatur magna dolore adipisicing labore. Elit aute laborum elit elit ullamco eu reprehenderit ex sit quis ea adipisicing occaecat veniam.\r\n',
    lat: 37.665883,
    lng: 175.844637,
  },
  {
    radius: 38,
    owner: 'Goff Douglas',
    address: '253 Freeman Street, Vale, Texas, 934',
    title: 'Ortiz Marshall title',
    description:
      'Quis sint est veniam consequat. Tempor do anim exercitation laborum ut elit deserunt. Sunt ad sunt Lorem minim sint. Ullamco nisi in laboris proident aliquip. Velit nisi sit aliquip laboris est laboris tempor aliqua ad ullamco ullamco dolor proident tempor. Ex nostrud proident consectetur proident commodo ipsum aliqua velit occaecat ad ipsum velit veniam occaecat.\r\n',
    lat: -67.197116,
    lng: -66.213108,
  },
  {
    radius: 32,
    owner: 'Adela Rush',
    address: '881 Delmonico Place, Lavalette, Pennsylvania, 5670',
    title: 'Lelia Burch title',
    description:
      'Reprehenderit nostrud minim exercitation proident irure adipisicing magna velit non est est aliquip exercitation magna. Ullamco tempor veniam est id elit officia excepteur incididunt anim. Adipisicing dolore aute nisi et exercitation. Aliquip voluptate ullamco veniam officia consequat tempor eu enim irure. Velit exercitation dolore ipsum incididunt exercitation dolor aliqua. Aliqua aliquip aute adipisicing occaecat est pariatur. Lorem Lorem sint minim enim deserunt aute est incididunt velit.\r\n',
    lat: -36.552658,
    lng: -138.701405,
  },
  {
    radius: 26,
    owner: 'Beatrice Ellis',
    address: '221 Applegate Court, Grapeview, Ohio, 3646',
    title: 'Lorna Taylor title',
    description:
      'Deserunt quis officia nulla quis reprehenderit magna elit duis occaecat cupidatat. Dolor consectetur sit et ex eiusmod occaecat minim sint quis et id non enim. Duis deserunt elit et eu consectetur Lorem dolor labore exercitation. Sit id veniam nisi velit elit adipisicing.\r\n',
    lat: -26.855567,
    lng: -118.43263,
  },
  {
    radius: 23,
    owner: 'Morin Barton',
    address: '617 Cyrus Avenue, Lutsen, Oregon, 3912',
    title: 'Berg Simpson title',
    description:
      'Velit dolor cillum reprehenderit consequat proident magna deserunt culpa. Laborum ea ex reprehenderit anim nostrud est est commodo id et do ipsum. Voluptate nisi labore ad consectetur sunt fugiat veniam aute laboris. Officia adipisicing veniam eiusmod consectetur sunt aute officia aute reprehenderit et excepteur adipisicing deserunt esse. Irure consequat ullamco non ad non id dolore. Irure dolor exercitation nostrud eu veniam. Culpa dolore in officia cupidatat est quis nisi nisi cupidatat.\r\n',
    lat: 55.521024,
    lng: 17.757717,
  },
  {
    radius: 40,
    owner: 'Sherman Russell',
    address: '447 Fleet Place, Helen, Wyoming, 4531',
    title: 'Anderson Espinoza title',
    description:
      'Esse amet ipsum esse non adipisicing quis. Nostrud mollit non reprehenderit eiusmod. Culpa tempor ipsum ut do aute et nulla voluptate incididunt in. Sint aliqua dolore et dolor. Et officia et consectetur do ullamco. Cupidatat aute consequat esse ullamco minim. Tempor id enim ex Lorem fugiat aliqua.\r\n',
    lat: 63.872053,
    lng: 86.046492,
  },
  {
    radius: 28,
    owner: 'Cathy Boyer',
    address: '994 Classon Avenue, Boyd, New Mexico, 8129',
    title: 'Veronica Fowler title',
    description:
      'Ad qui anim pariatur irure voluptate officia reprehenderit pariatur dolor. Aliquip aliquip ullamco aliqua id enim aute adipisicing consectetur. Do mollit ut ut nostrud pariatur. Velit qui voluptate commodo dolore. Excepteur eu amet velit ut nisi aute nisi velit anim. Ea id excepteur pariatur magna ullamco laborum Lorem ex culpa.\r\n',
    lat: -46.125391,
    lng: 147.124296,
  },
  {
    radius: 34,
    owner: 'Byrd Suarez',
    address: '187 Essex Street, Veyo, West Virginia, 1689',
    title: 'Young Goodman title',
    description:
      'Fugiat quis Lorem voluptate tempor duis. Nisi in enim velit commodo labore dolore minim nulla ullamco duis officia excepteur sit amet. Ullamco laborum consectetur eiusmod veniam elit. Veniam Lorem nostrud consectetur amet aliqua. Do reprehenderit laborum cupidatat cupidatat labore sint nisi velit do. Veniam officia dolor aliqua esse commodo velit anim non. Laborum aute duis occaecat ex proident fugiat in.\r\n',
    lat: 46.939352,
    lng: -87.741992,
  },
  {
    radius: 22,
    owner: 'Leonor Dennis',
    address: '198 Driggs Avenue, Swartzville, South Carolina, 1076',
    title: 'Hammond Wheeler title',
    description:
      'Duis mollit consectetur et reprehenderit non deserunt aliquip tempor excepteur officia. Aliqua voluptate eiusmod reprehenderit labore est ad ipsum minim voluptate velit labore deserunt. Nostrud adipisicing mollit incididunt nostrud sunt mollit quis ut magna dolor mollit id anim officia. Ea eiusmod exercitation veniam labore magna quis tempor in commodo cupidatat aliqua Lorem ut sunt. Anim cillum duis enim minim amet laborum elit ullamco culpa aliquip sunt sit irure. Amet labore eiusmod aliquip pariatur. Elit cillum nisi sunt laborum qui magna est in aliqua consequat mollit.\r\n',
    lat: 36.951503,
    lng: 178.663455,
  },
  {
    radius: 29,
    owner: 'Phoebe Riggs',
    address: '552 Linwood Street, Edinburg, Minnesota, 7605',
    title: 'Bass Owens title',
    description:
      'Non consectetur excepteur esse et consectetur id. Culpa ea sunt anim ut adipisicing cupidatat eiusmod proident commodo culpa aliquip labore proident. Deserunt eu id culpa aute Lorem laborum do laboris velit esse laboris consequat ullamco.\r\n',
    lat: 32.565658,
    lng: -94.710917,
  },
  {
    radius: 38,
    owner: 'Liz Dunlap',
    address: '308 Marconi Place, Carlton, Guam, 6023',
    title: 'Christensen England title',
    description:
      'Esse do sint occaecat incididunt enim voluptate sit minim est pariatur sint nostrud minim voluptate. Officia labore ex cillum cillum enim id dolor dolore dolore eu. Enim labore sint veniam commodo tempor ea ullamco ut eu. Id dolor irure reprehenderit pariatur non labore.\r\n',
    lat: -26.774716,
    lng: -49.780685,
  },
  {
    radius: 39,
    owner: 'Cardenas Snyder',
    address: '247 Friel Place, Steinhatchee, Marshall Islands, 5628',
    title: 'Mcclain Singleton title',
    description:
      'Cillum pariatur veniam nisi id duis. Enim occaecat minim ex enim. Tempor nulla aute et aliqua aute ad in laborum magna voluptate. Elit cillum ipsum officia sunt magna qui nostrud. Aute commodo occaecat commodo ipsum laborum dolor. Enim amet non qui non officia ex minim reprehenderit aute nisi adipisicing proident duis. Sunt ea eiusmod nulla qui eu enim duis reprehenderit.\r\n',
    lat: 26.865966,
    lng: 118.611197,
  },
  {
    radius: 40,
    owner: 'Kane Graves',
    address: '191 Moultrie Street, Bellfountain, South Dakota, 2719',
    title: 'Brennan Hawkins title',
    description:
      'Eu esse amet adipisicing esse enim fugiat consectetur adipisicing. Velit culpa ex deserunt voluptate commodo pariatur nisi qui ea labore sint ea consectetur nulla. Tempor adipisicing Lorem cupidatat aliquip velit. Consequat ut consequat ad laborum occaecat consectetur est id consectetur fugiat pariatur adipisicing aliqua ut. Nostrud magna aute excepteur proident enim reprehenderit sint amet eu magna. Cupidatat veniam ullamco ex mollit sint aliqua occaecat reprehenderit sit do ullamco mollit elit. Elit elit laborum sint et nostrud consequat amet sint aliqua qui.\r\n',
    lat: 88.227114,
    lng: 154.017666,
  },
  {
    radius: 28,
    owner: 'Shaffer Beard',
    address: '510 Miami Court, Sutton, Rhode Island, 1057',
    title: 'Caroline Vega title',
    description:
      'Culpa eu in magna irure occaecat exercitation sunt exercitation minim ex excepteur cupidatat eiusmod. Proident anim dolor sit anim nisi duis minim. Incididunt quis ea duis voluptate labore officia in sit incididunt Lorem velit ipsum laboris. Dolore in officia sit commodo proident aliquip quis. Ipsum deserunt et laboris minim ex. Excepteur aliquip deserunt deserunt aute quis amet ipsum magna ipsum aliquip nisi mollit quis.\r\n',
    lat: -56.746952,
    lng: -177.17706,
  },
  {
    radius: 28,
    owner: 'Shelley Garrison',
    address: '826 Kay Court, Wilmington, North Carolina, 1828',
    title: 'Blackwell Ray title',
    description:
      'Aliquip velit aute esse nisi eiusmod aliqua. Veniam incididunt minim Lorem culpa est ut eiusmod sit. Sint eiusmod in dolor sint commodo laboris dolore incididunt id. Dolore dolore ea labore qui dolore anim dolore aliquip in mollit incididunt aliquip sunt. Lorem Lorem veniam cillum quis duis tempor in fugiat anim incididunt mollit sit esse.\r\n',
    lat: -9.462428,
    lng: 121.225936,
  },
  {
    radius: 23,
    owner: 'Jennie Saunders',
    address: '492 Keen Court, Sussex, Virginia, 8112',
    title: 'Gina Craft title',
    description:
      'Tempor commodo nulla in nostrud. Ea nisi aliquip aliqua ad consectetur aliquip irure magna. Sunt ad irure nostrud aliquip eiusmod pariatur officia dolor ea. Anim anim anim labore nulla est occaecat nostrud.\r\n',
    lat: -0.012783,
    lng: -109.600592,
  },
  {
    radius: 29,
    owner: 'Vonda Webster',
    address: '854 Navy Street, Healy, Indiana, 2062',
    title: 'Cathleen Hardin title',
    description:
      'Nostrud laboris fugiat et aute aliquip consequat ut. Officia esse eiusmod culpa officia sunt id cillum consectetur incididunt aliqua ullamco mollit aliquip consequat. Culpa enim magna mollit quis occaecat tempor irure ullamco et. Incididunt veniam aliqua velit reprehenderit nulla laborum in reprehenderit commodo proident in.\r\n',
    lat: -74.110221,
    lng: -58.166335,
  },
];

export const users = [
  {
    fname: 'Param',
    lname: 'Singh',
    username: 'paramvst',
    email: 'param@sait.ca',
  },
  {
    fname: 'Lynden',
    lname: 'kid',
    username: 'lynden',
    email: 'Lynden.kidd@edu.sait.ca',
  },

  {
    fname: 'Jemal',
    lname: 'Colorado',
    username: 'jemal',
    email: 'Jemal.Colorado@edu.sait.ca',
  },
];

export const categories = [{ categoryName: 'Ice Cream Shop' }];
//   import {IoIosPeople} from "react-icons/io";
//   import {ImLocation} from "react-icons/im";
//   import {TriangleDownIcon}
export const routes = [
  {
    path: '/',
    owner: 'location',
    //   icon: <ImLocation />,
  },

  {
    path: '/',
    owner: 'Friends',
    //   icon: <IoIosPeople />,
  },
  {
    path: '/',
    owner: 'MemoryBank',
    //   icon: <TriangleDownIcon/>
  },
];

export const usernames = [
  { full_name: 'Farrel Hoggin' },
  { full_name: 'Irma Olech' },
  { full_name: 'Emmit Gallacher' },
  { full_name: 'Dunn Astlet' },
  { full_name: 'Burg Peaddie' },
  { full_name: 'Molli Knoller' },
  { full_name: 'Ellen Cheak' },
  { full_name: 'Kaela Hannibal' },
  { full_name: 'Roxanna Mughal' },
  { full_name: 'Sharona Robberts' },
  { full_name: 'Tybie Dudding' },
  { full_name: 'Reuben Beldan' },
  { full_name: 'Frannie Colter' },
  { full_name: 'Tobe Francescuccio' },
  { full_name: 'Hillary Selwyne' },
  { full_name: 'Bianka Lodford' },
  { full_name: 'Maureene Sleep' },
  { full_name: 'Guilbert Videler' },
  { full_name: 'Kin Juszkiewicz' },
  { full_name: 'Rosabella Droghan' },
  { full_name: 'Charmion Pretswell' },
  { full_name: 'Jada Corballis' },
  { full_name: 'Willey Kowal' },
  { full_name: 'Jimmie Apfelmann' },
  { full_name: 'Skelly Ramet' },
  { full_name: 'Jody Getcliffe' },
  { full_name: 'Ella Melendez' },
  { full_name: 'Archibold Meiklejohn' },
  { full_name: 'Sara Petty' },
  { full_name: 'Iosep Scotchmur' },
  { full_name: 'Bronnie Whitcomb' },
  { full_name: 'Hyatt Cattroll' },
  { full_name: 'Fidel Ferrucci' },
  { full_name: 'Sophi Jewess' },
  { full_name: 'Simeon Shann' },
  { full_name: 'Penn Arminger' },
  { full_name: 'Stanleigh Kitney' },
  { full_name: 'Zoe Bee' },
  { full_name: 'Nady Finn' },
  { full_name: 'Carlye Ridsdale' },
  { full_name: 'Anneliese Redmille' },
  { full_name: 'Lotti Frances' },
  { full_name: 'Roselia Donet' },
  { full_name: 'Alisander Besque' },
  { full_name: 'Robbie Shooter' },
  { full_name: 'Ebonee Fidelus' },
  { full_name: 'Mitchael MacLese' },
  { full_name: 'Boy Stannering' },
  { full_name: 'Roanna Echallier' },
  { full_name: 'Aggy Naish' },
  { full_name: 'Mirna Stokey' },
  { full_name: 'Angie Codd' },
  { full_name: 'Shepperd Duthie' },
  { full_name: 'Cristabel Vlasyuk' },
  { full_name: 'Petey Irvin' },
  { full_name: 'Sherline Jenton' },
  { full_name: 'Gladi Phifer' },
  { full_name: 'Sheree Low' },
  { full_name: 'Morgan Wellbank' },
  { full_name: 'Tybie Marczyk' },
  { full_name: 'Jaclyn Calafato' },
  { full_name: 'Wiley Dearnaley' },
  { full_name: 'Zelma Frankes' },
  { full_name: 'Ronny Yakubovich' },
  { full_name: 'Pall Jerok' },
];
